### ISSUE TITLE
Замечания по методу сопряжённых градиентов

### ISSUE THREAD

**Issue by dzheltkov** [DrEternity/Numerical_math_seminars_2#1]
1. От матрицы требуются только размеры и матвек, поэтому она должна передаваться в функцию, осуществляющую метод сопряжённых градиентов, или как размер и функция (лучше использовать `std::functional`, тогда возможно передать и класс с реализованным `operator()` ), или как шаблон, в котом реализованы операции `matvec` и, например, `order`.

**Comment by DrEternity** [comment]
Исправлено

**Comment by dzheltkov** [comment]
Всё хорошо, OpenMP и MPI задания приняты.

Единственное, скалярные произведения и axpy операции можно было бы распараллелить на OpenMP (в обеих версиях), только делать это нужно аккуратно, воспользовавшись условным оператором в директиве (чтобы не параллелилось или ичпользовалось меньше потоков для слишком коротких векторов). Но так как тестирование с плотными матрицами, то на тех размерах, что используются, это, в целом, не так важно (но для больших матриц может быть полезно).
Также в MPI версии можно было матвек распараллелить с помощью OpenMP.
